apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: petdemo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: petdemo
    spec:
      containers:
        - name: actuator-sample
          image: registry.gitlab.com/rickmmmmm/petdemo
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: registry.gitlab.com